server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: dbc:mysql://192.168.6.112:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true

mybatis:
  mapper-locations: classpath:mapper/*.xml

netty:
  port: 8081